---
- hosts: all
  become: yes
  tasks:
    - name: update apt cache
      apt: update_cache=yes
      when: ansible_os_family == "Debian"
    - name: update yum cache
      yum: update_cache=yes
      when: ansible_os_family == "RedHat"
